const Language = {
  en: {
    welcome: "Welcome",
    total_patient: "Total Patients",
    earnings: "Earnings",
    total: "Total",
    pending: "Pending",
    completed: "Completed",
    my_appointments: "My Appointments",
    age: "Age",
    years: "years",
    type: "Type",
    time: "Time",
    status: "Status",
    bill: "Bill",
    view_more: "view more",
    weekly: "weekly",
    monthly: "monthly",
    yearly: "yearly",
    ascending: "ascending",
    descending: "descending",
    start_visit: "start visit",
    billing: "billing",
    reschedule: "reschedule",
    cancel: "cancel",
    search_patient: "Search Patient",
    all: "All",
    new: "New",
    follow_up: "Follow up",
    report_review: "Report Review",
    routine: "Routine",
    contact:"Contact",
    add_me: "Add me",
    phone_number:'Phone Number',
    login:'Login',
    signup:'Signup',
    otp:'OTP',
    submit:'Submit',
    password:'Password'
  },
  hi: {
    welcome: "स्वागत",
    total_patient: "कुल रोगी",
    earnings: "आय",
    total: "कुल",
    pending: "लंबित",
    completed: "संपन्न",
    my_appointments: "मेरी नियुक्ति",
    age: "आयु",
    years: "साल",
    type: "प्रकार",
    time: "समय",
    status: "स्थिति",
    bill: "बिल",
    view_more: "और देखें",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    yearly: "वार्षिक",
    ascending: "आरोही",
    descending: "अवरोही",
    start_visit: "मुआइना",
    billing: "बिलिंग",
    reschedule: "पुनर्निर्धारित",
    cancel: "निरस्त",
    search_patient: "रोगी खोजें",
    all: "सभी",
    new: "नया",
    follow_up: "फ़ॉलो अप",
    report_review: "रिपोर्ट समीक्षा",
    routine: "रूटीन",
    phone_number:'Phone Number'
   
  },
  ta: {
    welcome: "வருகை வாழ்த்துக்கள்",
    total_patient: "மொத்த பேரருக்கு",
    earnings: "சம்பாதிக்கை",
    total: "மொத்தம்",
    pending: "நிலுவை",
    completed: "நிறைவு",
    my_appointments: "எனது அமர்வுகள்",
    age: "வயது",
    years: "வருடங்கள்",
    type: "வகை",
    time: "நேரம்",
    status: "நிலைமை",
    bill: "பில்",
    view_more: "மேலும் பார்க்க",
    weekly: "வாராந்திர",
    monthly: "மாதாந்திர",
    yearly: "வருடாந்திர",
    ascending: "உயரியாகும்",
    descending: "குறையாகும்",
    start_visit: "பாராட்டு தொடங்குக",
    billing: "பில்கள்",
    reschedule: "மறுக்கப்பட்டது",
    cancel: "ரத்துசெய்",
    search_patient: "பேரரை தேடு",
    all: "அனைத்த",
    new: "புதியது",
    follow_up: "பின்னூட்டம்",
    report_review: "அறிக்கை மதிப்பாய்வு",
    routine: "ரூடின்"
  }
};

export {Language};
