export const CONSTANTS = {
  modes: ['Injection', 'Capsule', 'Syrup', 'Tablet'],
  medicine_recomendation: ['Avil', 'Paracetmol', 'Dolo650', 'Citrizen'],
  dose: ['500mg', '700mg', '800mg', '1000mg'],
  timing: ['AF', 'BF'],
  frequency: ['Morning', 'Noon', 'Evening', 'Night'],
  speciality: ['cardialogist', 'general_physician', 'gynogologist'],
  consultTypes: ['Physical', 'Telephonic', 'Online'],
  duration: [10, 15, 20, 25, 30],
  abhaOption: ["Don't Have ABHA_ID", 'Have ABHA_ID'],
  role: ['Practitioner', 'Administator', 'patient'],
  clinic: ['Rasi Clinic', 'Magizh Clinic', 'Kamatchi Clinic'],
  success: 'success',
  error: 'error',
  warning: 'warning',
  selections: ['New', 'Follow Up', 'Report Review', 'Routine'],
  prescription: ['Prescription', 'Blood Report', 'Scan'],
};
