const Language = {
  en: {
    welcome: 'Welcome',
    total_patient: 'Total Patients',
    earnings: 'Earnings',
    total: 'Total',
    pending: 'Pending',
    completed: 'Completed',
    my_appointments: 'My Appointments',
    age: 'Age',
    years: 'years',
    type: 'Type',
    time: 'Time',
    status: 'Status',
    bill: 'Bill',
    view_more: 'view more',
    weekly: 'weekly',
    monthly: 'monthly',
    yearly: 'yearly',
    ascending: 'ascending',
    descending: 'descending',
    start_visit: 'start visit',
    billing: 'billing',
    reschedule: 'reschedule',
    cancel: 'cancel',
    search_patient: 'Search Patient',
    all: 'All',
    new: 'New',
    follow_up: 'Follow up',
    report_review: 'Report Review',
    routine: 'Routine',
    contact: 'Contact',
    add_me: 'Add me',
    phone_number: 'Phone Number',
    login: 'Login',
    signup: 'Signup',
    otp: 'OTP',
    submit: 'Submit',
    password: 'Password',
    no_account: "Don't have an account?",
    yes_account: 'Already registered?',
    password_2: 'Password 2',
    otp_placeholder: '4 digit OTP',
    resend_otp: 'Resend OTP',
    forgot_password: 'Forgot your password?',
    forgot_placeholder: 'Reset Password',
    appointments: 'Appointments',
    dr: ' Dr. ',
    doctor: ' Doctor. ',
    start_visit: 'Start Visit',
    reschedule: 'Reschedule',
    cancel: 'Cancel',
  },
  hi: {
    welcome: 'स्वागत',
    total_patient: 'कुल रोगी',
    earnings: 'आय',
    total: 'कुल',
    pending: 'लंबित',
    completed: 'संपन्न',
    my_appointments: 'मेरी नियुक्ति',
    age: 'आयु',
    years: 'साल',
    type: 'प्रकार',
    time: 'समय',
    status: 'स्थिति',
    bill: 'बिल',
    view_more: 'और देखें',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    yearly: 'वार्षिक',
    ascending: 'आरोही',
    descending: 'अवरोही',
    start_visit: 'मुआइना',
    billing: 'बिलिंग',
    reschedule: 'पुनर्निर्धारित',
    cancel: 'निरस्त',
    search_patient: 'रोगी खोजें',
    all: 'सभी',
    new: 'नया',
    follow_up: 'फ़ॉलो अप',
    report_review: 'रिपोर्ट समीक्षा',
    routine: 'रूटीन',
    phone_number: 'फ़ोन नंबर',
    login: 'लॉग इन करें',
    signup: 'साइन अप करें',
    otp: 'ओ.टी.पी',
    submit: 'जमा करना',
    password: 'पासवर्ड',
    no_account: 'खाता नहीं है?',
    yes_account: 'पहले से ही पंजीकृत?',
    password_2: 'पासवर्ड २',
    otp_placeholder: '४ अंकों का ओ.टी.पी',
    resend_otp: 'ओ.टी.पी पुनः भेजें',
    forgot_password: 'अपना पासवर्ड भूल गए?',
    forgot_placeholder: 'पासवर्ड बनाएं',
    appointments: 'नियुक्ति',
    dr: ' डॉ. ',
    start_visit: 'दौरा शुरू करें',
    reschedule: 'पुनर्निर्धारित',
    cancel: 'रद्द करना ',
  },
  ta: {
    welcome: 'வருகை வாழ்த்துக்கள்',
    total_patient: 'மொத்த பேரருக்கு',
    earnings: 'சம்பாதிக்கை',
    total: 'மொத்தம்',
    pending: 'நிலுவை',
    completed: 'நிறைவு',
    my_appointments: 'எனது அமர்வுகள்',
    age: 'வயது',
    years: 'வருடங்கள்',
    type: 'வகை',
    time: 'நேரம்',
    status: 'நிலைமை',
    bill: 'பில்',
    view_more: 'மேலும் பார்க்க',
    weekly: 'வாராந்திர',
    monthly: 'மாதாந்திர',
    yearly: 'வருடாந்திர',
    ascending: 'உயரியாகும்',
    descending: 'குறையாகும்',
    start_visit: 'பாராட்டு தொடங்குக',
    billing: 'பில்கள்',
    reschedule: 'மறுக்கப்பட்டது',
    cancel: 'ரத்துசெய்',
    search_patient: 'பேரரை தேடு',
    all: 'அனைத்த',
    new: 'புதியது',
    follow_up: 'பின்னூட்டம்',
    report_review: 'அறிக்கை மதிப்பாய்வு',
    routine: 'ரூடின்',
    phone_number: 'தொலைபேசி எண்',
    login: 'உள்நுழைய',
    signup: 'பதிவு',
    otp: 'OTP',
    submit: 'சமர்ப்பிக்கவும்',
    password: 'கடவுச்சொல்',
    no_account: 'கணக்கு இல்லையா?',
    yes_account: 'ஏற்கனவே பதிவு செய்யப்பட்டது?',
    start_visit: 'வருகை தொடங்க',
    reschedule: 'மறு அட்டவணை',
    cancel: 'ரத்து செய்',
  },
};

export {Language};
