const Language = {
  en: {
    welcome: 'Welcome',
    total_patient: 'Total Patients',
    earnings: 'Earnings',
    total: 'Total',
    pending: 'Pending',
    completed: 'Completed',
    my_appointments: 'My Appointments',
    age: 'Age',
    years: 'years',
    type: 'Type',
    time: 'Time',
    status: 'Status',
    bill: 'Bill',
    view_more: 'See all',
    weekly: 'weekly',
    monthly: 'monthly',
    yearly: 'yearly',
    ascending: 'ascending',
    descending: 'descending',
    start_visit: 'start visit',
    billing: 'billing',
    reschedule: 'reschedule',
    cancel: 'cancel',
    search_patient: 'Search Patient',
    all: 'All',
    new: 'New',
    follow_up: 'Follow up',
    report_review: 'Report Review',
    routine: 'Routine',
    contact: 'Contact',
    add_me: 'Add me',
    phone_number: 'Phone Number',
    login: 'Login',
    signup: 'Signup',
    otp: 'OTP',
    submit: 'Submit',
    password: 'Password',
    no_account: "Don't have an account?",
    yes_account: 'Already registered?',
    password_2: 'Password 2',
    otp_placeholder: '4 digit OTP',
    resend_otp: 'Resend OTP',
    forgot_password: 'Forgot your password?',
    forgot_placeholder: 'Reset Password',
    appointments: 'Appointments',
    dr: ' Dr. ',
    doctor: ' Doctor. ',
    symptoms: 'Symptoms',
    days: 'Days',
    severity: 'Severity',
    prescribe: 'Prescribe',
    mode: 'Mode',
    medicine: 'Medicine',
    reccomedations: 'Recommedations',
    number: 'Number',
    timing: 'Timing',
    frequency: 'Frequency',
    duration: 'Duration',
    quantity: 'Quantity',
    dose: 'Dose',
    update: 'update',
    delete: 'delete',
    consultation: 'Consultation',
    cheif_complaints: 'Cheif Complaints',
    suggestions: 'Suggestions',
    vitals: 'Vitals',
    pulse_rate: 'Pulse rate',
    weight: 'Weight',
    height: 'Height',
    temp: 'Temp',
    rate: 'Res.Rate',
    bmi: 'BMI',
    diastolic_bp: 'Diastolic BP',
    systolic_bp: 'Systolic BP',
    lmp_edd: 'LMP EDD',
    us_edd: 'US EDD',
    notes: 'Notes',
    recommendation: 'Recommendations',
    getotp: 'Get Otp',
    name: 'Name',
    gender: 'Gender',
    dob: 'Date of Birth',
    medical_number: 'Medical Number',
    specialization: 'Specialization',
    experience: 'Experience',
    save: 'Save',
    clinic: 'Clinic',
    fees: 'Consultation Fees',
    address: 'Address',
    buildingno: 'Building No.',
    street: 'Street',
    role: 'Role',
    successfully_abha_created: 'Successfully ABHA Created',
    addnew: 'Add New',
    verify: 'Verify',
    aadhar: 'Aadhar No',
    abha: 'ABHA ID',
    search_result: 'Search Results',
    wait: 'Wait We are setting Up...',
    medium: 'Medium',
    low: 'Low',
    high: 'High',
    complaint: 'Complaint',
    book_appointment: 'Book Appointment',
    history: 'Medical History',
    // complaint: 'Complaint',
    diagnosis: 'Diagnosis',
    // symptoms: 'Symptoms',
    // prescribe: 'Prescribe',
    refer_doctor: 'Refer a Doctor',
    specialist: 'specialist',
    ph: 'Ph',
    test: 'Test Prescribed',
  },
  hi: {
    welcome: 'स्वागत',
    total_patient: 'कुल रोगी',
    earnings: 'आय',
    total: 'कुल',
    pending: 'लंबित',
    completed: 'संपन्न',
    my_appointments: 'मेरी नियुक्ति',
    age: 'आयु',
    years: 'साल',
    type: 'प्रकार',
    time: 'समय',
    status: 'स्थिति',
    bill: 'बिल',
    view_more: 'और देखें',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    yearly: 'वार्षिक',
    ascending: 'आरोही',
    descending: 'अवरोही',
    start_visit: 'मुआइना',
    billing: 'बिलिंग',
    reschedule: 'पुनर्निर्धारित',
    cancel: 'निरस्त',
    search_patient: 'रोगी खोजें',
    all: 'सभी',
    new: 'नया',
    follow_up: 'फ़ॉलो अप',
    report_review: 'रिपोर्ट समीक्षा',
    routine: 'रूटीन',
    phone_number: 'फ़ोन नंबर',
    login: 'लॉग इन करें',
    signup: 'साइन अप करें',
    otp: 'ओ.टी.पी',
    submit: 'जमा करना',
    password: 'पासवर्ड',
    no_account: 'खाता नहीं है?',
    yes_account: 'पहले से ही पंजीकृत?',
    password_2: 'पासवर्ड २',
    otp_placeholder: '४ अंकों का ओ.टी.पी',
    resend_otp: 'ओ.टी.पी पुनः भेजें',
    forgot_password: 'अपना पासवर्ड भूल गए?',
    forgot_placeholder: 'पासवर्ड बनाएं',
    appointments: 'नियुक्ति',
    dr: ' डॉ. ',
    symptoms: 'लक्षण',
    days: 'दिन',
    severity: 'तीव्रता',
    prescribe: 'सलाह देना',
    mode: 'तरीका',
    medicine: 'दवा',
    reccomedations: 'सिफारिशों',
    number: 'संख्या',
    timing: 'समय',
    frequency: 'आवृत्ति',
    duration: 'अवधि',
    quantity: 'मात्रा',
    dose: 'खुराक',
  },
  ta: {
    welcome: 'வருகை வாழ்த்துக்கள்',
    total_patient: 'மொத்த பேரருக்கு',
    earnings: 'சம்பாதிக்கை',
    total: 'மொத்தம்',
    pending: 'நிலுவை',
    completed: 'நிறைவு',
    my_appointments: 'எனது அமர்வுகள்',
    age: 'வயது',
    years: 'வருடங்கள்',
    type: 'வகை',
    time: 'நேரம்',
    status: 'நிலைமை',
    bill: 'பில்',
    view_more: 'மேலும் பார்க்க',
    weekly: 'வாராந்திர',
    monthly: 'மாதாந்திர',
    yearly: 'வருடாந்திர',
    ascending: 'உயரியாகும்',
    descending: 'குறையாகும்',
    start_visit: 'பாராட்டு தொடங்குக',
    billing: 'பில்கள்',
    reschedule: 'மறுக்கப்பட்டது',
    cancel: 'ரத்துசெய்',
    search_patient: 'பேரரை தேடு',
    all: 'அனைத்த',
    new: 'புதியது',
    follow_up: 'பின்னூட்டம்',
    report_review: 'அறிக்கை மதிப்பாய்வு',
    routine: 'ரூடின்',
    phone_number: 'தொலைபேசி எண்',
    login: 'உள்நுழைய',
    signup: 'பதிவு',
    otp: 'OTP',
    submit: 'சமர்ப்பிக்கவும்',
    password: 'கடவுச்சொல்',
    no_account: 'கணக்கு இல்லையா?',
    yes_account: 'ஏற்கனவே பதிவு செய்யப்பட்டது?',
    symptoms: 'அறிகுறிகள்',
    days: 'நாட்களில்',
    severity: 'தீவிரம்',
    prescribe: 'பரிந்துரை',
    mode: 'முறை',
    medicine: 'மருந்து',
    reccomedations: 'பரிந்துரைகள்',
    number: 'எண்',
    timing: 'நேரம்',
    frequency: 'அதிர்வெண்',
    duration: 'கால அளவு',
    quantity: 'அளவு',
    dose: 'டோஸ்',
  },
};

export {Language};
